TOP 20 FUNCTIONS IN PANDAS

Pandas is a python library used for data analysis & data manipulation.

1. Reading a file

In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('/content/sample_data/SalesData.csv')

2. Get the top ans bottom of the dataset

head() displays the first 5 rows of a DataFrame by default.

In [5]:
df.head()

           DateTime           Product  Quantity  Unit_Price  Revenue
0  2024-06-15 11:35          Baguette      10.0        2.94    29.40
1  2024-10-13 10:58  Cheesecake Slice       9.0        4.98    44.82
2  2024-03-02 15:05     Almond Danish      10.0        3.42    34.20
3  2024-01-20 07:01   Sourdough Bread      13.0        5.40    70.20
4  2024-07-26 13:08   Sourdough Bread      11.0        5.42    59.62

tail() displays the last 5 rows of a DataFrame by default.

In [6]:
df.tail()

               DateTime            Product  Quantity  Unit_Price  Revenue
11630  2024-12-23 09:37            Brownie      11.0        2.29    25.19
11631  2024-06-22 12:09          Croissant       8.0        2.76    22.08
11632  2024-06-28 12:11  Carrot Cake Slice      21.0        4.29    90.09
11633  2024-02-03 09:36  Carrot Cake Slice      13.0        4.40    57.20
11634  2024-09-03 10:25    Sourdough Bread      12.0        5.72    68.64

3. Get the complete information about all the columns in the table

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11635 entries, 0 to 11634
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   DateTime    11635 non-null  object
 1   Product     11635 non-null  object
 2   Quantity    11628 non-null  float64
 3   Unit_Price  11627 non-null  float64
 4   Revenue     11635 non-null  float64
dtypes: float64(3), object(2)
memory usage: 454.6+ KB

It provides a summary of the DataFrame, including the number of rows, columns, non-null values, data types, and memory usage.

4. We also can see the shape and size of the dataset.

shape is a Pandas attribute (not a function) that tells you the number of rows and columns in a DataFrame.

In [8]:
df.shape

(11635, 5)

size is a Pandas attribute that returns the total number of elements (cells) in a DataFrame.

In [9]:
df.size

58175

5. Choose a number of random sample from the dataset.

sample() is a Pandas function that returns random rows from a DataFrame.

In [11]:
df.sample(n=10)

               DateTime           Product  Quantity  Unit_Price  Revenue
285    2024-12-10 08:20  Chocolate Muffin      11.0        2.61    28.71
463    2024-08-28 10:12  Chocolate Muffin      11.0        2.55    28.05
10338  2024-12-14 11:08     Cinnamon Roll      11.0        3.27    35.97
8967   2024-08-17 09:34     Cinnamon Roll      11.0        3.16    34.76
6956   2024-08-01 10:24      Banana Bread      16.0        4.13    66.08
3452   2024-08-18 09:44          Baguette       8.0        3.10    24.80
3342   2024-03-03 10:02  Blueberry Muffin      12.0        2.54    30.48
715    2024-02-22 12:36           Brownie      12.0        2.28    27.36
6230   2024-04-19 09:17     Almond Danish      13.0        3.63    47.19
3148   2024-04-20 12:05         Croissant       9.0        2.78    25.02

n = Number of random rows you want.

6. Get the standard mathematical analysis of each column of dataset

describe() is a Pandas function that gives summary statistics of the numerical columns in a DataFrame.

In [12]:
df.describe()

           Quantity    Unit_Price       Revenue
count  11628.000000  11627.000000  11635.000000
mean      10.954850      3.302217     36.387309
std        2.920719      1.009286     15.752053
min       -1.000000      2.090000     -5.770000
25%        9.000000      2.550000     25.900000
50%       11.000000      2.930000     32.100000
75%       13.000000      3.880000     43.680000
max       23.000000      5.770000    111.100000

In [13]:
df.describe().T

              count       mean        std   min    25%    50%    75%     max
Quantity    11628.0  10.954850   2.920719 -1.00   9.00  11.00  13.00   23.00
Unit_Price  11627.0   3.302217   1.009286  2.09   2.55   2.93   3.88    5.77
Revenue     11635.0  36.387309  15.752053 -5.77  25.90  32.10  43.68  111.10

describe().T is used to transpose the output of describe().
.T changes rows into columns and columns into rows (Transpose).

7. Find no. of distinct values - This is an important function as it will directly tell you how many categorical variables are there in your dataset

unique() returns all distinct (unique) values in a column.

A DataFrame has multiple columns, but unique() works only on a single column (Series).

In [16]:
df["Product"].unique()

array(['Baguette', 'Cheesecake Slice', 'Almond Danish', 'Sourdough Bread',
       'Carrot Cake Slice', 'Chocolate Muffin', 'Cinnamon Roll',
       'Croissant', 'Blueberry Muffin', 'Brownie', 'Focaccia',
       'Banana Bread'], dtype=object)

nunique() returns the number of unique values in a column.

In [18]:
df.nunique()

DateTime      11207
Product          12
Quantity         23
Unit_Price      346
Revenue        2486
dtype: int64

8.How do you check if the DataFrame has any missing values?

isna() and isnull() do the same thing in Pandas.
You can use either one.

In [19]:
df.isna().any()

DateTime      False
Product       False
Quantity       True
Unit_Price     True
Revenue       False
dtype: bool

True → The DataFrame contains missing values.


False → No missing values are present.

9.How do you check missing values in each column?

In [20]:
df.isnull().sum()

DateTime      0
Product       0
Quantity      7
Unit_Price    8
Revenue       0
dtype: int64

10. How do you count the total missing values?

In [21]:
df.isnull().sum().sum()

np.int64(15)

11. Get the names of the column

In [23]:
df.columns

Index(['DateTime', 'Product', 'Quantity', 'Unit_Price', 'Revenue'], dtype='object')

12. Get the nsmallest or nlargest values from a column

nsmallest() returns the smallest n rows based on a specified column.

df.nsmallest(n, "Column_Name")

n = Number of rows you want.
"Column_Name" = Column to sort by.

In [24]:
df.nsmallest(5, "Quantity")

             DateTime            Product  Quantity  Unit_Price  Revenue
13   2024-08-11 08:50  Carrot Cake Slice      -1.0        4.58    -4.58
35   2024-08-23 09:30   Blueberry Muffin      -1.0        2.38    -2.38
133  2024-12-29 10:35  Carrot Cake Slice      -1.0        4.61    -4.61
359  2024-12-30 12:37          Croissant      -1.0        2.76    -2.76
389  2024-11-17 09:34      Almond Danish      -1.0        3.44    -3.44

nlargest() returns the largest n rows based on a specified column.

In [28]:
df.nlargest(5,'Revenue')

               DateTime           Product  Quantity  Unit_Price  Revenue
3386   2024-06-16 13:28  Cheesecake Slice      22.0        5.05   111.10
5048   2024-09-15 07:40  Cheesecake Slice      22.0        4.97   109.34
5110   2024-07-14 09:21  Cheesecake Slice      22.0        4.97   109.34
10583  2024-02-17 12:33  Cheesecake Slice      22.0        4.87   107.14
5342   2024-10-11 09:21  Cheesecake Slice      20.0        5.23   104.60

These both function can be apply on numerical data only.

13.How do you check how much memory a DataFrame or its columns use in Pandas?

Use df.memory_usage() to check the memory used by each column.

In [29]:
df.memory_usage()

Index           132
DateTime      93080
Product       93080
Quantity      93080
Unit_Price    93080
Revenue       93080
dtype: int64

Use df.memory_usage(deep=True) for accurate memory usage, especially for string columns.

In [30]:
df.memory_usage(deep=True)

Index            132
DateTime      756275
Product       711972
Quantity       93080
Unit_Price     93080
Revenue        93080
dtype: int64

Use df.info(memory_usage="deep") to see the total memory usage of the DataFrame.

In [31]:
df.info(memory_usage="deep")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11635 entries, 0 to 11634
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   DateTime    11635 non-null  object
 1   Product     11635 non-null  object
 2   Quantity    11628 non-null  float64
 3   Unit_Price  11627 non-null  float64
 4   Revenue     11635 non-null  float64
dtypes: float64(3), object(2)
memory usage: 1.7 MB

14. Which Pandas function is used to write a DataFrame to a CSV file?

The to_csv() function is used to save a DataFrame as a CSV file.

In [35]:
df.to_csv('SalesData.csv', index = False)

Why do we use index=False in to_csv()?

By default, Pandas saves the row index (0, 1, 2, ...).


Using index=False prevents the index from being written to the CSV file, making the file cleaner and easier to use in Excel, SQL, or other tools.

15. Slicing with loc and iloc

loc - Uses row/column labels (names)
loc[] selects data using row labels and column names.

iloc - Uses row/column positions (numbers)
iloc[] selects data using row numbers and column numbers.

Select one row

In [51]:
df.loc[7]

DateTime      2024-11-10 09:50
Product        Sourdough Bread
Quantity                  12.0
Unit_Price                5.33
Revenue                  63.96
Name: 7, dtype: object

Select one row and one column

In [52]:
df.loc[2, "Product"]

'Almond Danish'

Select multiple rows

In [58]:
df.loc[2:3]

           DateTime          Product  Quantity  Unit_Price  Revenue
2  2024-03-02 15:05    Almond Danish      10.0        3.42     34.2
3  2024-01-20 07:01  Sourdough Bread      13.0        5.40     70.2

Select specific columns

In [59]:
df.loc[:, ["Product", "Quantity"]]

                 Product  Quantity
0               Baguette      10.0
1       Cheesecake Slice       9.0
2          Almond Danish      10.0
3        Sourdough Bread      13.0
4        Sourdough Bread      11.0
...                  ...       ...
11630            Brownie      11.0
11631          Croissant       8.0
11632  Carrot Cake Slice      21.0
11633  Carrot Cake Slice      13.0
11634    Sourdough Bread      12.0

[11635 rows x 2 columns]

In [44]:
df.iloc[7,1]

'Sourdough Bread'

Row position = 7
Column position = 0 (Name)

Select multiple rows



in iloc[], the last row (4) is not included.

In [45]:
df.iloc[1:4]

           DateTime           Product  Quantity  Unit_Price  Revenue
1  2024-10-13 10:58  Cheesecake Slice       9.0        4.98    44.82
2  2024-03-02 15:05     Almond Danish      10.0        3.42    34.20
3  2024-01-20 07:01   Sourdough Bread      13.0        5.40    70.20

Get only the product abd revenue columns

In [46]:
df.loc[:, ["Product", "Revenue"]]

                 Product  Revenue
0               Baguette    29.40
1       Cheesecake Slice    44.82
2          Almond Danish    34.20
3        Sourdough Bread    70.20
4        Sourdough Bread    59.62
...                  ...      ...
11630            Brownie    25.19
11631          Croissant    22.08
11632  Carrot Cake Slice    90.09
11633  Carrot Cake Slice    57.20
11634    Sourdough Bread    68.64

[11635 rows x 2 columns]

Get rows 5 to 10 and columns 1 to 3

In [47]:
df.iloc[5:11,1:4]

              Product  Quantity  Unit_Price
5   Carrot Cake Slice      13.0        4.42
6    Chocolate Muffin      10.0        2.59
7     Sourdough Bread      12.0        5.33
8   Carrot Cake Slice       9.0        4.59
9       Cinnamon Roll       8.0        3.27
10    Sourdough Bread      16.0        5.36

Select first two columns

In [50]:
df.iloc[:, 0:2]

               DateTime            Product
0      2024-06-15 11:35           Baguette
1      2024-10-13 10:58   Cheesecake Slice
2      2024-03-02 15:05      Almond Danish
3      2024-01-20 07:01    Sourdough Bread
4      2024-07-26 13:08    Sourdough Bread
...                 ...                ...
11630  2024-12-23 09:37            Brownie
11631  2024-06-22 12:09          Croissant
11632  2024-06-28 12:11  Carrot Cake Slice
11633  2024-02-03 09:36  Carrot Cake Slice
11634  2024-09-03 10:25    Sourdough Bread

[11635 rows x 2 columns]

Which one includes the last value while slicing?


loc[] → Includes the last label.
iloc[] → Excludes the last position.

16. Sorting


we use the sort_values() function to sort data.

sorting in descending order

In [60]:
df.sort_values(by="DateTime" , ascending = False)

              DateTime           Product  Quantity  Unit_Price  Revenue
9572  2024-12-31 16:08  Blueberry Muffin      13.0        2.45    31.85
2679  2024-12-31 14:44     Cinnamon Roll       9.0        3.13    28.17
8422  2024-12-31 13:14      Banana Bread      16.0        4.01    64.16
6894  2024-12-31 13:13          Focaccia      10.0        4.08    40.80
952   2024-12-31 13:12           Brownie      10.0        2.29    22.90
...                ...               ...       ...         ...      ...
2104  2024-01-01 08:06      Banana Bread       9.0        3.92    35.28
9914  2024-01-01 08:06   Sourdough Bread      10.0        5.55    55.50
1053  2024-01-01 07:17   Sourdough Bread      11.0        5.63    61.93
9363  2024-01-01 07:14           Brownie      10.0        2.24    22.40
1373  2024-01-01 07:05         Croissant      12.0        2.90    34.80

[11635 rows x 5 columns]

In [61]:
df.sort_index(ascending = False)

               DateTime            Product  Quantity  Unit_Price  Revenue
11634  2024-09-03 10:25    Sourdough Bread      12.0        5.72    68.64
11633  2024-02-03 09:36  Carrot Cake Slice      13.0        4.40    57.20
11632  2024-06-28 12:11  Carrot Cake Slice      21.0        4.29    90.09
11631  2024-06-22 12:09          Croissant       8.0        2.76    22.08
11630  2024-12-23 09:37            Brownie      11.0        2.29    25.19
...                 ...                ...       ...         ...      ...
4      2024-07-26 13:08    Sourdough Bread      11.0        5.42    59.62
3      2024-01-20 07:01    Sourdough Bread      13.0        5.40    70.20
2      2024-03-02 15:05      Almond Danish      10.0        3.42    34.20
1      2024-10-13 10:58   Cheesecake Slice       9.0        4.98    44.82
0      2024-06-15 11:35           Baguette      10.0        2.94    29.40

[11635 rows x 5 columns]

In [63]:
df.sort_values(by=["Product","Revenue"], ascending=[True,False])

              DateTime          Product  Quantity  Unit_Price  Revenue
7883  2024-07-17 11:23    Almond Danish      22.0        3.64    80.08
2871  2024-07-03 12:02    Almond Danish      22.0        3.62    79.64
3360  2024-10-08 09:44    Almond Danish      23.0        3.41    78.43
9255  2024-03-06 09:05    Almond Danish      22.0        3.56    78.32
9065  2024-03-18 09:32    Almond Danish      23.0        3.37    77.51
...                ...              ...       ...         ...      ...
4542  2024-09-15 08:10  Sourdough Bread      -1.0        5.51    -5.51
1631  2024-02-10 10:08  Sourdough Bread      -1.0        5.56    -5.56
2872  2024-07-03 12:16  Sourdough Bread      -1.0        5.60    -5.60
6307  2024-07-07 08:37  Sourdough Bread      -1.0        5.73    -5.73
743   2024-04-25 10:20  Sourdough Bread      -1.0        5.77    -5.77

[11635 rows x 5 columns]

17. Grouping

Grouping is the process of dividing data into groups based on one or more columns using groupby().

In [65]:
df.groupby("Product")["Quantity"].count()

Product
Almond Danish         736
Baguette              871
Banana Bread          554
Blueberry Muffin      945
Brownie              1216
Carrot Cake Slice     512
Cheesecake Slice      433
Chocolate Muffin     1491
Cinnamon Roll        1306
Croissant            2049
Focaccia              382
Sourdough Bread      1133
Name: Quantity, dtype: int64

In [66]:
df.groupby("Product")["Revenue"].sum()

Product
Almond Danish        30182.51
Baguette             29580.73
Banana Bread         27655.47
Blueberry Muffin     26455.09
Brownie              29068.00
Carrot Cake Slice    28175.92
Cheesecake Slice     25762.05
Chocolate Muffin     39027.89
Cinnamon Roll        44797.08
Croissant            58947.67
Focaccia             17050.19
Sourdough Bread      66663.74
Name: Revenue, dtype: float64

In [67]:
df.groupby("Product")["Revenue"].mean()

Product
Almond Danish        41.008845
Baguette             33.922856
Banana Bread         49.829676
Blueberry Muffin     27.994804
Brownie              23.884963
Carrot Cake Slice    55.031094
Cheesecake Slice     59.223103
Chocolate Muffin     26.175647
Cinnamon Roll        34.300980
Croissant            28.754961
Focaccia             44.634005
Sourdough Bread      58.786367
Name: Revenue, dtype: float64

18. Rename Columns

In [68]:
df.rename(columns={"Product":"Product Name"})

               DateTime       Product Name  Quantity  Unit_Price  Revenue
0      2024-06-15 11:35           Baguette      10.0        2.94    29.40
1      2024-10-13 10:58   Cheesecake Slice       9.0        4.98    44.82
2      2024-03-02 15:05      Almond Danish      10.0        3.42    34.20
3      2024-01-20 07:01    Sourdough Bread      13.0        5.40    70.20
4      2024-07-26 13:08    Sourdough Bread      11.0        5.42    59.62
...                 ...                ...       ...         ...      ...
11630  2024-12-23 09:37            Brownie      11.0        2.29    25.19
11631  2024-06-22 12:09          Croissant       8.0        2.76    22.08
11632  2024-06-28 12:11  Carrot Cake Slice      21.0        4.29    90.09
11633  2024-02-03 09:36  Carrot Cake Slice      13.0        4.40    57.20
11634  2024-09-03 10:25    Sourdough Bread      12.0        5.72    68.64

[11635 rows x 5 columns]

19. Query in dataframe

In [70]:
df.query('Revenue < 20')

               DateTime            Product  Quantity  Unit_Price  Revenue
13     2024-08-11 08:50  Carrot Cake Slice      -1.0        4.58    -4.58
25     2024-03-16 07:24   Blueberry Muffin       7.0        2.44    17.08
35     2024-08-23 09:30   Blueberry Muffin      -1.0        2.38    -2.38
50     2024-03-30 12:49            Brownie       6.0        2.22    13.32
59     2024-03-30 07:11            Brownie       8.0        2.29    18.32
...                 ...                ...       ...         ...      ...
11555  2024-01-07 11:21   Blueberry Muffin       8.0        2.39    19.12
11556  2024-07-07 09:25            Brownie       8.0        2.22    17.76
11562  2024-02-10 10:46          Croissant       7.0        2.66    18.62
11577  2024-08-25 11:41            Brownie       8.0        2.26    18.08
11605  2024-09-21 09:36            Brownie       8.0        2.10    16.80

[836 rows x 5 columns]

In [77]:
df.query("Product =='Brownie'")

               DateTime  Product  Quantity  Unit_Price  Revenue
36     2024-04-28 09:40  Brownie      10.0        2.27    22.70
43     2024-03-08 10:44  Brownie      10.0        2.28    22.80
50     2024-03-30 12:49  Brownie       6.0        2.22    13.32
57     2024-04-05 10:29  Brownie      12.0        2.23    26.76
59     2024-03-30 07:11  Brownie       8.0        2.29    18.32
...                 ...      ...       ...         ...      ...
11613  2024-02-15 07:01  Brownie      13.0        2.27    29.51
11615  2024-06-16 12:57  Brownie      12.0        2.13    25.56
11616  2024-06-25 15:12  Brownie      14.0        2.16    30.24
11627  2024-01-19 10:53  Brownie      14.0        2.10    29.40
11630  2024-12-23 09:37  Brownie      11.0        2.29    25.19

[1217 rows x 5 columns]

20. Merging

In [10]:
import pandas as pd

employees = pd.DataFrame({
    "Emp_ID": [101, 102, 103],
    "Name": ["Amit", "Priya", "Rahul"]
})

In [11]:
salary = pd.DataFrame({
    "Emp_ID": [101, 102, 104],
    "Salary": [40000, 50000, 60000]
})

Merge the dataframes

In [80]:
pd.merge(employees, salary, on="Emp_ID")

   Emp_ID   Name  Salary
0     101   Amit   40000
1     102  Priya   50000

Types of Merge

There are 4 main types of joins in Pandas.

1. Inner Join (Default)

Returns only matching rows.

In [6]:
pd.merge(employees, salary, on="Emp_ID" , how="inner")

   Emp_ID   Name  Salary
0     101   Amit   40000
1     102  Priya   50000

2. Left Join

Returns all rows from the left DataFrame and matching rows from the right.

In [15]:
import pandas as pd
pd.merge(employees, salary, on="Emp_ID", how="left")

   Emp_ID   Name   Salary
0     101   Amit  40000.0
1     102  Priya  50000.0
2     103  Rahul      NaN

3. Right Join

Returns all rows from the right DataFrame and matching rows from the left.

In [16]:
pd.merge(employees, salary, on="Emp_ID", how="right")

   Emp_ID   Name  Salary
0     101   Amit   40000
1     102  Priya   50000
2     104    NaN   60000

4. Outer Join

Returns all rows from both DataFrames.

In [17]:
pd.merge(employees, salary, on="Emp_ID", how="outer")

   Emp_ID   Name   Salary
0     101   Amit  40000.0
1     102  Priya  50000.0
2     103  Rahul      NaN
3     104    NaN  60000.0